/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rockchip_gpadc_ssddemo_InferenceWrapper */

#ifndef _Included_com_rockchip_gpadc_ssddemo_InferenceWrapper
#define _Included_com_rockchip_gpadc_ssddemo_InferenceWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rockchip_gpadc_ssddemo_InferenceWrapper
 * Method:    init
 * Signature: (IIIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rockchip_gpadc_ssddemo_InferenceWrapper_init
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring);

/*
 * Class:     com_rockchip_gpadc_ssddemo_InferenceWrapper
 * Method:    native_deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rockchip_gpadc_ssddemo_InferenceWrapper_native_1deinit
  (JNIEnv *, jobject);

/*
 * Class:     com_rockchip_gpadc_ssddemo_InferenceWrapper
 * Method:    native_run
 * Signature: ([B[F[F)I
 */
JNIEXPORT jint JNICALL Java_com_rockchip_gpadc_ssddemo_InferenceWrapper_native_1run___3B_3F_3F
  (JNIEnv *, jobject, jbyteArray, jfloatArray, jfloatArray);

/*
 * Class:     com_rockchip_gpadc_ssddemo_InferenceWrapper
 * Method:    native_run
 * Signature: (I[F[F)I
 */
JNIEXPORT jint JNICALL Java_com_rockchip_gpadc_ssddemo_InferenceWrapper_native_1run__I_3F_3F
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray);

/*
 * Class:     com_rockchip_gpadc_ssddemo_InferenceWrapper
 * Method:    native_create_direct_texture
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_rockchip_gpadc_ssddemo_InferenceWrapper_native_1create_1direct_1texture
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rockchip_gpadc_ssddemo_InferenceWrapper
 * Method:    native_delete_direct_texture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rockchip_gpadc_ssddemo_InferenceWrapper_native_1delete_1direct_1texture
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
